object frmRemoteClient: TfrmRemoteClient
  Left = 204
  Top = 116
  HorzScrollBar.Visible = False
  VertScrollBar.Visible = False
  BorderStyle = bsNone
  Caption = 'tttRemoteScreen'
  ClientHeight = 472
  ClientWidth = 709
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poDesigned
  WindowState = wsMaximized
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnKeyUp = FormKeyUp
  OnMouseWheel = FormMouseWheel
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 709
    Height = 24
    Align = alTop
    AutoSize = True
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitTop = 448
    ExplicitWidth = 701
    object Label1: TLabel
      Left = 706
      Top = 0
      Width = 3
      Height = 24
      Align = alRight
      Color = clInfoBk
      ParentColor = False
      Layout = tlCenter
      ExplicitLeft = 698
    end
    object btnConnect: TSpeedButton
      Left = 370
      Top = 2
      Width = 70
      Height = 22
      Caption = 'Connect'
      Flat = True
      Visible = False
      OnClick = btnConnectClick
    end
    object btnDisconnect: TSpeedButton
      Left = 444
      Top = 2
      Width = 70
      Height = 22
      Caption = 'Disconnect'
      Enabled = False
      Flat = True
      Visible = False
      OnClick = btnDisconnectClick
    end
    object cbControl: TCheckBox
      Left = 0
      Top = 6
      Width = 60
      Height = 17
      Caption = 'Control'
      TabOrder = 1
    end
    object cbStretch: TCheckBox
      Left = 64
      Top = 6
      Width = 97
      Height = 17
      Caption = 'Stretch'
      TabOrder = 0
      OnClick = cbStretchClick
    end
  end
  object ScrollBox1: TScrollBox
    Left = 0
    Top = 24
    Width = 709
    Height = 448
    HorzScrollBar.Visible = False
    VertScrollBar.Visible = False
    Align = alClient
    BorderStyle = bsNone
    Color = clBlack
    Ctl3D = False
    ParentColor = False
    ParentCtl3D = False
    TabOrder = 1
    ExplicitWidth = 693
    ExplicitHeight = 409
    object pbScreen: TPaintBox
      Left = 0
      Top = 0
      Width = 105
      Height = 105
      OnMouseDown = pbScreenMouseDown
      OnMouseMove = pbScreenMouseMove
      OnMouseUp = pbScreenMouseUp
      OnPaint = pbScreenPaint
    end
  end
end
